const fs = require('fs');
const path = require('path');

const hiPath = path.join(__dirname, 'src/locales/hi/common.json');
let hiData = JSON.parse(fs.readFileSync(hiPath, 'utf8'));

const updates = {
  "login": "अंदर आएं",
  "signup": "खाता बनाएं",
  "home": "मुख्य पृष्ठ",
  "search": "खोजें",
  "apply": "लागू करें",
  "selectFilters": "विकल्प चुनें",
  "bookYourAppointment": "मिलने का समय तय करें",
  "startAssessment": "जांच शुरू करें",
  "viewProfile": "अपनी जानकारी देखें",
  "bookASession": "बातचीत का समय तय करें",
  "viewPricing": "कीमत देखें",
  "learnMore": "और जानें",
  "startYourJourney": "अपनी शुरुआत करें",
  "findYourMatch": "सही जानकार खोजें",
  "viewDemo": "उदाहरण देखें",
  "joinCommunity": "लोगों से जुड़ें",
  "links": "लिंक",
  "expertSector": "जानकार का क्षेत्र",
  "wellnessSector": "सेहत का क्षेत्र",
  "educationSector": "शिक्षा का क्षेत्र",
  "financeSector": "पैसे का क्षेत्र",
  "appliedFiltersPlaceholder": "चुने गए विकल्प यहां दिखेंगे",
  "welcomeBack": "फिर से स्वागत है!",
  "emailOrPhone": "ईमेल या फोन",
  "password": "पासवर्ड",
  "forgotPassword": "पासवर्ड भूल गए?",
  "dontHaveAccount": "खाता नहीं है?",
  "signUpItsFree": "खाता बनाएं, यह मुफ्त है!",
  "createAccount": "खाता बनाएं",
  "yourRole": "आप क्या हैं?",
  "user": "ग्राहक",
  "expert": "जानकार",
  "fullName": "पूरा नाम",
  "email": "ईमेल",
  "phoneNo": "फोन नंबर",
  "alreadyHaveAccount": "पहले से खाता है?",
  "assessmentComplete": "जांच पूरी हुई!",
  "personalizedAssessment": "यह आपका निजी परिणाम है",
  "saveAssessmentResult": "परिणाम सेव करें",
  "retakeAssessment": "फिर से जांच करें",
  "goToHomepage": "मुख्य पृष्ठ पर जाएं",
  "expertVerifiedAssessments": "जानकारों द्वारा बनाई गई जांच",
  "takePreScreenerTests": "हमारी आसान जांच करें और अपनी रिपोर्ट पाएं। यह बताएगा कि शुरुआत कहां से करनी है।",
  "clinicallyValidatedTests": "डॉक्टरों द्वारा जांची गई जांच",
  "getAnswersUnder3Minutes": "3 मिनट में जवाब पाएं और अपनी मानसिक सेहत समझें।",
  "takeAssessment": "जांच करें",
  "takeFreeAssessment": "मुफ्त जांच करें",
  "mentalWellnessProfessionals": "मानसिक सेहत के जानकार",
  "certifiedPioneerProfessionals": "प्रमाणित जानकार",
  "livesTransformed": "बदले हुए जीवन",
  "specializedTools": "खास तरीके",
  "wellness": "सेहत",
  "wellnessSubtitle": "सेहत सबसे बड़ी दौलत है",
  "wellnessDescription": "तनाव कम करें, ऊर्जा बढ़ाएं और संतुलित जीवन जिएं।",
  "education": "शिक्षा",
  "educationSubtitle": "अच्छी शिक्षा बेहतर भविष्य बनाती है",
  "educationDescription": "सही पढ़ाई और काम के लिए आसान और साफ सलाह पाएं।",
  "finance": "पैसा",
  "financeSubtitle": "पैसे का सही उपयोग जरूरी है",
  "financeDescription": "मजबूत आर्थिक आधार बनाएं और सुरक्षित भविष्य पाएं।",
  "expertVerifiedAssessmentsBadge": "जानकारों द्वारा प्रमाणित जांच",
  "discoverYourPath": "सही जानकारों की मदद से <highlight>बेहतर फैसले</highlight> लें",
  "heroSubheading": "अनुभवी लोगों से बात करें और अपनी राह आसान बनाएं",
  "expertsFallbackDescription": "आसान मार्गदर्शन और मदद पाएं",
  "wellnessExpertsBadge": "आसान सेहत मदद",
  "wellnessExpertsTitleLine1": "आपकी यात्रा",
  "wellnessExpertsTitleLine2": "बेहतर सेहत की ओर",
  "wellnessExpertsSubtitle": "सहानुभूति रखने वाले लोग आपको बेहतर महसूस करने में मदद करेंगे",
  "educationExpertsBadge": "आसान काम और पढ़ाई मदद",
  "educationExpertsTitleLine1": "आसान सलाह से",
  "educationExpertsTitleLine2": "अपना भविष्य बनाएं",
  "educationExpertsSubtitle": "पढ़ाई और काम के लिए साफ और आसान सलाह पाएं",
  "expertsChooseHeading": "अपना क्षेत्र चुनें",
  "expertsChooseSubheading": "जहां आपको जल्दी और आसान मदद चाहिए, वह चुनें",
  "financeHeroBadge": "आसान पैसों का मार्गदर्शन",
  "financeHeroTitle": "आत्मविश्वास से अपना आर्थिक भविष्य बनाएं",
  "financeHeroSubtitle": "भरोसेमंद लोगों से आसान सलाह लें और पैसों के फैसले सरल बनाएं",
  "financeChooseHeading": "अपना क्षेत्र चुनें",
  "financeChooseSubheading": "जहां आपको मदद चाहिए, वह क्षेत्र चुनें",
  "financeFallbackDescription": "आसान मार्गदर्शन और मदद पाएं",
  "freeAssessments": "मुफ्त जांच",
  "startFreeAssessment": "मुफ्त जांच शुरू करें",
  "findYourExpert": "अपना जानकार खोजें",
  "getFreeConsultation": "मुफ्त सलाह पाएं",
  "exploreOurExpertCategories": "हमारी श्रेणियां देखें",
  "connectWithVerified": "सेहत, शिक्षा और पैसे के भरोसेमंद जानकारों से जुड़ें",
  "assessMentalHealth": "अपनी मानसिक सेहत जांचें",
  "planCareerEducational": "अपने काम और पढ़ाई की योजना बनाएं",
  "buildFinancialFoundation": "अपनी आर्थिक नींव मजबूत करें",
  "mentalHealthAssessment": "मानसिक सेहत की जांच",
  "careerPlanning": "काम की योजना",
  "financialPlanning": "पैसों की योजना",
  "indiasOwnVirtualCounselling": "भारत का अपना ऑनलाइन सलाह मंच",
  "certifiedIndianProfessionals": "प्रमाणित भारतीय जानकार",
  "licensedCounselorsTherapists": "लाइसेंस प्राप्त सलाहकार, डॉक्टर और पोषण जानकार",
  "careerFinancialAdvisors": "काम और पैसे के सलाहकार",
  "academicAdvisorsCareer": "शिक्षा, काम और पैसे के सलाहकार",
  "makeInIndiaDescription": "माइंड क्योर पाथ 'मेक इन इंडिया' का समर्थन करता है। हम लोगों को प्रमाणित भारतीय जानकारों से जोड़ते हैं ताकि सही और सस्ती सलाह मिल सके।",
  "trueGrowthBegins": "हम मानते हैं कि असली विकास अंदर से शुरू होता है। यह भारत का अपना ऑनलाइन सलाह मंच है — भारतीयों के लिए बनाया गया।",
  "newsletter": "जानकारी के लिए जुड़े रहें",
  "stayUpToDate": "नई खबरें और ऑफर पाने के लिए जुड़े रहें",
  "enterYourEmailAddress": "अपना ईमेल लिखें",
  "subscribe": "जुड़ें",
  "guidanceQuotesHeading": "बेहतर नतीजों के लिए सही मार्गदर्शन चुनें",
  "guidanceQuotesSubtitle": "समय और पैसा लगाने से पहले, इन्हें पढ़ने के लिए 30 सेकंड लें",
  "guidanceQuotesInsight": "सीख {{number}}",
  "guidanceQuotesWhatToDoNext": "अब क्या करें",
  "guidanceQuotesCardDescription": "एक जानकार द्वारा बनाई गई जांच से शुरुआत करें और साफ अगले कदम जानें।",
  "guidanceQuotesStartFreeAssessment": "मुफ्त जांच शुरू करें",
  "guidanceQuotesMeetExperts": "जानकारों से मिलें",
  "guidanceQuotesQuote1": "सही जानकार से सलाह लेकर अपनी सोच और फैसले बेहतर बनाएं।",
  "guidanceQuotesQuote2": "अनुभवी लोगों से सलाह लें, गलत सलाह नुकसान कर सकती है।",
  "guidanceQuotesQuote3": "समय की कीमत समझें, गलत रास्ते पर समय बर्बाद न करें।",
  "whyChooseUsTitle": "हमें क्यों चुनें?",
  "whyChooseUsExpertVerifiedTitle": "जानकारों द्वारा प्रमाणित",
  "whyChooseUsExpertVerifiedDescription": "सभी जांच जानकारों द्वारा बनाई गई हैं",
  "whyChooseUsConfidentialTitle": "100% सुरक्षित",
  "whyChooseUsConfidentialDescription": "आपकी जानकारी सुरक्षित है और किसी से साझा नहीं की जाती",
  "whyChooseUsAvailableTitle": "हमेशा उपलब्ध",
  "whyChooseUsAvailableDescription": "कभी भी, कहीं भी जांच करें",
  "whyChooseUsGuidanceTitle": "निजी मार्गदर्शन",
  "whyChooseUsGuidanceDescription": "भरोसेमंद जानकारों से सीधे जुड़ें",
  "footerTagline": "जानकारों की सलाह और सच्ची देखभाल",
  "quickLinks": "जरूरी लिंक",
  "support": "मदद",
  "legal": "कानूनी जानकारी",
  "findCounsellors": "सलाहकार खोजें",
  "wellnessAssessments": "सेहत की जांच",
  "educationAssessments": "शिक्षा की जांच",
  "financeAssessments": "पैसों की जांच",
  "selectAssessment": "शुरू करने के लिए एक जांच चुनें।",
  "helpCenter": "मदद केंद्र",
  "contact": "संपर्क करें",
  "faq": "अक्सर पूछे जाने वाले सवाल",
  "privacyPolicy": "गोपनीयता नीति",
  "termsAndConditions": "नियम और शर्तें",
  "termsOfUse": "उपयोग के नियम",
  "allRightsReserved": "सभी अधिकार सुरक्षित।",
  "footerDisclaimerLabel": "जरूरी सूचना:",
  "footerDisclaimerText": "माइंड क्योर पाथ एक ऑनलाइन मंच है जो लोगों को स्वतंत्र जानकारों से जोड़ता है। हम डॉक्टरी सलाह या इलाज नहीं देते। यह आपातकाल के लिए नहीं है। मानसिक आपात स्थिति में राष्ट्रीय हेल्पलाइन 1800-599-0019 या नजदीकी आपात सेवा से संपर्क करें।",
  
  // NEW MISSING KEYS FROM LANDING PAGE
  "heroRatingTrusted": "10,000+ लोगों का भरोसा",
  "heroRatingScore": "4.8/5",
  "heroDesignSub": "सही जानकारों से बात करें, अपने विकल्प समझें और बेहतर भविष्य की ओर कदम बढ़ाएं।",
  "heroDesignCtaPrimary": "अभी जानकार से बात करें",
  "heroDesignCtaSecondary": "मुफ्त जांच करें",
  "heroDesignTrustUsers": "10,000+ खुश लोग",
  "heroDesignTrustExpert": "जानकारों द्वारा जांची गई",
  "heroDesignTrustPrivate": "100% सुरक्षित और गोपनीय",
  "heroDesignPartnersLabel": "इनके जानकारों का भरोसा",
  "heroCardExplore": "और देखें",
  "heroCardWellnessBody": "तनाव कम करें, अच्छी आदतें बनाएं और संतुलित जीवन जिएं।",
  "heroCardFinanceBody": "पैसों की सही योजना बनाएं, समझदारी से फैसले लें और सुरक्षित भविष्य बनाएं।",
  "heroCardEducationBody": "सही रास्ता चुनें, अपना काम बढ़ाएं और भविष्य बेहतर बनाएं।"
};

for (const [key, value] of Object.entries(updates)) {
  hiData[key] = value;
}

fs.writeFileSync(hiPath, JSON.stringify(hiData, null, 2), 'utf8');
console.log('Successfully updated hi/common.json');
